os: linux
dist: bionic

language:
    - cpp
    
        
before_install:
    - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "kostsm"
    token:
      secure: "sgAQOMHwhEMFD+3R3xrH6fODvuSG6AjwrCycCypuRhfXQy3L1EcwUP4NNPWXBhogfigx1c8sV/ExPhfpL7C0Gth6nTmlBYTlm+oZMcGPqTb/rPcoZLt4gSpqprgd58V9H8khitBkXfw5vH1IhfnoubpYTCfi6SqXSGHa5SctblG+RTmt59iX4IGBxtUWMUcy8cNEEHjc+ZLe4jS9xCvTSTaN1iNbhQGRHybDcdtrhljnCjAG4W22+7akghTZym2HEqC7cGMQEzGOVwxbPJwpahBZmaFHY2mmb6oe48Pi5nFrEcAKZ6p9mLDHD8xFlr7J9Uuuis2M5jPm2MFCSOarAm3bP31aDuHRQlPtKUhjNZTk+bQ8e/Zz56DrGh9Q3fJpA8xvm4ogP26PZfShsKTWV+N/6CaDrmGs+BkVbmfNYutkT/Yp7xneXwYAQ4dnsaiq7sLsYzlFccJGsRpxacnVlD6i0qXfGCN5Zp2sjw/ELfe9pbqKNSPX5VqXYIHyxGvyyh3+01MbtS+sD/boZq2hxqUIQn9zAHHvR8gEx6Ud5Nabv/TzjR/k3cHo3vaXjFN96+GcQxzRnNqvRRQj0cpyknsoztiSZaYKRS5qVdl44sjh8CrExPPsfV+IipRBk0JaJ7kF6OO1A1mab3SY0xBctE3bhkjRBJMcVHz2HLnEmcE="

script:
    - qmake 
    - make
    - ./tests/tests
    
after_success:
    - coveralls --root . -E ".*external.*" -E ".*tests.*"
    - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
    - sonar-scanner
    
cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    
notifications:
    email: false 
